let namesFind = [{
    isPopular: true,
    image: "CSS/Photo/Rectangle 22.png",
    heading: "Париж",
    text: "9 дней | 12 дней поездка в Нормандию и Париж",
    price: 138000 ,
    crossedPrice:"150 000 руб.",
    button: "Выбрать",
    id: 1,
},
{
    isPopular: true,
    image: "Css/Photo/Rectangle 23 .png",
    heading: "Италия, Манарола",
    text: "12 дней | 14 дней с поездкой в Рим",
    price: 175000 ,
    crossedPrice:"190 000 руб.",
    button: "Выбрать",
    id: 2,
},
{  
    isPopular: true,
    image: "CSS/Photo/Rectangle 24.png",
    heading: "Италия, Рим",
    text: "11 дней | 14 дней с поездкой в Мадрид",
    price: 200000 ,
    crossedPrice:"230 000 руб.",
    button: "Выбрать",
    id: 3,
},{
    isPopular: false,
    image: "CSS/Photo/Rectangle 25.png",
    heading: "Италия, Венеция",
    text: "9 дней | 11 дней с поездкой в Сорренто",
    price: 155000 ,
    crossedPrice:"177 000 руб.",
    button: "Выбрать",
    id: 4,
},{
    isPopular: false,
    image: "CSS/Photo/Rectangle 26.png",
    heading: "Тур по Испании",
    text: "14 дней | 16 дней с поездкой в Барселону",
    price: 200000 ,
    crossedPrice:"210 000 руб.",
    button: "Выбрать",
    id: 5,
},{
    isPopular: false,
    image: "CSS/Photo/Rectangle 27.png",
    heading: "Бразилия, Рио",
    text: "Рио, водопады Игуасу и Буэнос-Айрес",
    price: 225000 ,
    crossedPrice:"240 000 руб.",
    button: "Выбрать",
    id: 6,
},{
    isPopular: false,
    image: "CSS/Photo/Rectangle 28.png",
    heading: "Хельсинки",
    text: "Скандинавия: столицы и фьорды",
    price: 215000 ,
    crossedPrice:"230 000 руб.",
    button: "Выбрать",
    id: 7,
},{
    isPopular: false,
    image: "CSS/Photo/Rectangle 31.png",
    heading: "Лондон",
    text: "9 дней | 11 дней с поездкой в Париж",
    price: 285000 ,
    crossedPrice:"295 000 руб.",
    button: "Выбрать",
    id: 8,
},{
    isPopular: false,
    image: "CSS/Photo/Rectangle 32.png",
    heading: "Аляска",
    text: "Национальный парк Денали и круиз по дикой Аляске",
    price: 300000 ,
    crossedPrice:"310 000 руб.",
    button: "Выбрать",
    id: 9,
}
]